repos:
  # Black code formatting
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.11
        exclude: ^(instance/|attached_assets/|docs/|.*\.sql$)

  # isort import sorting
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
        exclude: ^(instance/|attached_assets/|docs/)

  # Flake8 linting
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        exclude: ^(instance/|attached_assets/|docs/|.*\.sql$)
        additional_dependencies:
          - flake8-docstrings
          - flake8-import-order

  # MyPy type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests
          - types-flask
          - types-setuptools
        exclude: ^(instance/|attached_assets/|docs/|scripts/debug_.*\.py$|.*\.sql$)

  # General code quality checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      # Remove trailing whitespace
      - id: trailing-whitespace
        exclude: ^(instance/|attached_assets/)
      # Ensure files end with newline
      - id: end-of-file-fixer
        exclude: ^(instance/|attached_assets/)
      # Check for files that would conflict on case-insensitive filesystems
      - id: check-case-conflict
      # Check for merge conflict markers
      - id: check-merge-conflict
      # Check YAML files
      - id: check-yaml
        exclude: ^(instance/|attached_assets/)
      # Check JSON files
      - id: check-json
        exclude: ^(instance/|attached_assets/)
      # Check for Python syntax errors
      - id: check-ast
        exclude: ^(instance/|attached_assets/)
      # Check for debugger imports
      - id: debug-statements
        exclude: ^(instance/|attached_assets/|scripts/debug_.*\.py$)

  # Security scanning
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
      - id: bandit
        args: ["-r", ".", "-x", "instance,attached_assets,docs"]
        exclude: ^(instance/|attached_assets/|docs/|scripts/debug_.*\.py$)

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false